name: Weekly Scraper
on:
  schedule:
    - cron: '0 9 * * 1' # every Monday 9 AM UTC
  workflow_dispatch:
jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install selenium gspread google-auth webdriver-manager

      - name: Create credentials.json
        run: echo "${{ secrets.GOOGLE_CREDS }}" > credentials.json
      - name: Run scraper
        run: python scraper.py

